name: flutter_reorderable_list
description: Reorderable list for flutter.
version: 1.2.0
homepage: https://github.com/knopp/flutter_reorderable_list

environment:
  sdk: ">=2.12.0 <4.6.1"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
